name: Go Build and Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/hugo.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/hugo.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to run workflow for'
        required: true
  release:
    types: [published]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        if: github.event_name != 'workflow_dispatch'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check out code into the Go module directory
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
        id: go

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test on ubuntu
        run: |
          go install gotest.tools/gotestsum@latest
          gotestsum --jsonfile=report.json --rerun-fails --packages=./... -- -race -covermode=atomic -coverprofile=cover.out

      - name: SonarCloud Scan
        if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload test and coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            report.json
            cover.out

  build-binaries:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out code into the Go module directory
        if: ${{ !contains(github.event_name, 'workflow_dispatch') }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check out code into the Go module directory
        if: ${{ contains(github.event_name, 'workflow_dispatch') }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
        id: go

      - run: make protodoc-linux-{amd64,arm64,armv7}
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - run: make protodoc-macos-{amd64,arm64} protodoc-windows-amd64
        if: ${{ matrix.os == 'macos-latest' }}

      - name: Upload protodoc dist
        uses: actions/upload-artifact@v2
        with:
          name: protodoc-${{ matrix.os }}-dist
          path: protodoc-*

  build-dist:
    name: Build release
    needs: [build-and-test, build-binaries]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        if: ${{ !contains(github.event_name, 'workflow_dispatch') }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check out code into the Go module directory
        if: ${{ contains(github.event_name, 'workflow_dispatch') }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}

      - name: Download ubuntu protodoc binaries
        uses: actions/download-artifact@v2
        with:
          name: protodoc-ubuntu-latest-dist

      - name: Download macos protodoc binaries
        uses: actions/download-artifact@v2
        with:
          name: protodoc-macos-latest-dist

      - run: make dist

      - name: Upload protodoc release
        uses: actions/upload-artifact@v2
        with:
          name: protodoc-release-binaries
          path: protodoc-*.zip

  build_and_push_docker_multiarch:
    name: Build and push multiarch docker image
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs: [build-and-test, build-binaries]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        if: ${{ !contains(github.event_name, 'workflow_dispatch') }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check out code into the Go module directory
        if: ${{ contains(github.event_name, 'workflow_dispatch') }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}

      - name: Download protodoc binary
        uses: actions/download-artifact@v2
        with:
          name: protodoc-ubuntu-latest-dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          cp protodoc-linux-amd64 protodoc
          ls -R protodoc*
          chmod a+rx protodoc protodoc-*

      - name: Build and push release Docker Image (main-ghcr)
        run: make docker_multiarch DOCKER_IMAGE=ghcr.io/manugarg/protodoc

  pre-release:
    name: Upload pre-release binaries
    if: github.ref == 'refs/heads/main'
    needs: [build-dist]
    runs-on: ubuntu-latest

    steps:
      - name: Download protodoc release
        uses: actions/download-artifact@v2
        with:
          name: protodoc-release-binaries
      - run: ls -R *
      - run: |
          mv protodoc*-linux-arm64.zip protodoc-tip-linux-arm64.zip
          mv protodoc*-linux-armv7.zip protodoc-tip-linux-armv7.zip
          mv protodoc*-linux-x86_64.zip protodoc-tip-linux-x86_64.zip
          mv protodoc*-macos-arm64.zip protodoc-tip-macos-arm64.zip
          mv protodoc*-macos-x86_64.zip protodoc-tip-macos-x86_64.zip
          mv protodoc*-windows-x86_64.zip protodoc-tip-windows-x86_64.zip
      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            protodoc-*.zip
